### ISSUE TITLE
Original attribute order is not preserved

### ISSUE THREAD

**Issue by tomuxmon** [faassen/xot#9]
Hello. Me again :).  Spotted that the attribute order is not preserved when using `to_string`. Is there a way to somehow preserve it? In my project, I want to be as conservative as possible. Best demonstrated with a test:

```rust
#[test]
fn test_atribute_reorder() {
    let mut xot = Xot::new();
    let original_xml = r#"<data name="some" xml:space="preserve"/>"#;
    let root = xot.parse(original_xml).unwrap();
    assert_eq!(original_xml, xot.to_string(root).unwrap());
}
```

Test output:
```
running 1 test
thread 'serializer::tests::test_atribute_reorder' panicked at src/serializer.rs:350:9:
assertion `left == right` failed
  left: "<data name=\"some\" xml:space=\"preserve\"/>"
 right: "<data xml:space=\"preserve\" name=\"some\"/>"
```

Would appreciate any help or guidance on where should I try to improve "xot" regarding attribute order.

**Comment by faassen** [comment]
Strictly speaking the order of attributes is not part of the XML data model, as you also indicate. But I can see that getting the same order out would be desirable.

So let's think about it a bit:

The attributes are stored in a BTreeMap, which stores the keys in sorted order, and delivers them too. The keys are name ids, internally increased each time a new name/ns combination is seen.

So it depends on the previous order in which the names were encountered in elements and attributes what order the keys come out.

This means that to guarantee a roundtrip, the attribute order needs to be stored on each element.  What is a new attribute is added programmatically? I guess we could put it at the end of the order.

An API would be required to get the attributes in order; like `attributes_in_order`. It could return an iterator over the name,value pairs.

The serializer would then need to be modified to use this information.

There are costs involved to store information that isn't really part of XML. In particular, 
I would ideally like to avoid using extra space in all elements to store this information, but that looks tricky.

An alternative is not to use BTreeMap but some type of ordered map. In the past in fact I used a structure like this that simply stores it in a vector (since not many attributes exist on a node this is fast enough). But it wasn't implementing the full map API. Perhaps we can find a good alternative?

**Comment by faassen** [comment]
This is what I was using in the past:

https://docs.rs/vector-map/latest/vector_map/

But it's not implementing the full map API. 

See here for the history:

https://github.com/faassen/xot/issues/6

Maybe litemap would have the right characteristics?

**Comment by faassen** [comment]
Looks like litemap sorts its keys so it's out.

I would like a map that is really just a vector of key value pairs but implements the Map API.

inserting a new key would always push to the end of the vec.

Since an XML element is unlikely to have more than a few attributes this should be fast enough.

**Comment by faassen** [comment]
I'm glad the change was so easy! It's still a signficant change but I'm happy to move ahead with it.

I am not worried about performance; I suspect `vecmap-rs` is going to perform at least as well for typical cases as BTreeMap. Linear search is going to be very fast for small amounts of attributes as it's just a `NameId` comparison and it can race through a short vec very quickly.

Do you want to put up a PR? With a couple of attribute reorder tests; I think we need to confirm that insert adds the attribute to the end, and deleting also doesn't change the order of other attributes.

**Comment by faassen** [comment]
I've now implemented this (also for prefixes) and it's in the latest version! Thanks for asking about this!
